### ISSUE TITLE
Chargebee doesn't work properly

### ISSUE THREAD

**Issue by ghost** [chargebee/chargebee-rails-sample#1]
My problem with chargebee-rails-sample are:

- When I click Process to Payment, the popup doesn't open. I have to use Dev Tools to modify CSS, and the popup is open
- When I click "Cancel", the popup doesn't close. I see in Dev Tools, the request was complete 
- When I click "Subscribe", the request was complete and the subscription was added to chargebee. But the popup doesn't close, redirect doesn't work and subscription data don't store in my DB

I've stored my code at [https://github.com/jenkijo/chargebee-rails-sample](https://github.com/jenkijo/chargebee-rails-sample)

**Comment by sai92messy** [comment]
@jenkijo I checked the source code, and noticed the `site_name:` not having a proper value.

```ruby
# customers_controller.rb
...

  def hosted_page_checkout_new
    hosted_page = ChargeBee::HostedPage.checkout_new(
      subscription: { plan_id: params[:plan_id] },
      card: {gateway: "chargebee"},
      customer: customer_params,
      embed: true,
      iframe_messaging: true
    ).hosted_page
    render json: {
      url: hosted_page.url,
      hosted_page_id: hosted_page.id,
      site_name: ENV["CHARGEBEE_SITE"] # make sure you mention the chargebee_site name here
    }
  end
```

**Comment by sai92messy** [comment]
Closing this issue.
